# Default values for jupyter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

passwd: ""

image:
  repository: modernroboticsplatform/jupyter
  tag: ""

serviceAccount:
  create: false

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true 
  hosts:
    - host: "" 
      paths: 
       - "/jupyter" 
